import type { Metadata } from "next";
import { GoogleAnalytics } from "@next/third-parties/google";
import Navbar from "@/components/navbar";
import Providers from "@/components/providers";
import "./globals.css";


export const metadata: Metadata = {
  title: "Combat Wombats FTC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body suppressHydrationWarning className="">
        <Providers>
          <main className="font-mona bg-beige text-black dark:bg-gradient-to-r from-darkbeige to-darkerbeige dark:text-white">
            <Navbar />
            {children}
          </main>
        </Providers>
      </body>
      <GoogleAnalytics gaId="G-FWM87P8M7Z" />
    </html>
  );
}
